import type { CodegenConfiguration } from "src/types/CodegenConfiguration";
import { getHookNames } from "src/utils/getHookNames";
import { getImportSpecifier } from "src/utils/getImportSpecifier";

/** Aliases only when the names differ, so the common case reads as a plain import. */
const importBinding = (exported: string, local: string) => {
  if (exported === local) {
    return local;
  }

  return `${exported} as ${local}`;
};

export const GENERATED_HEADER =
  "// Generated by simulcast-codegen. Do not edit.\n";

// Every binding exports these three names so one template serves React, Vue, Solid, and Svelte.
const DEFAULT_RUNTIME = "simulcast-react";

export const renderHooks = (
  configuration: CodegenConfiguration,
  events: string[],
) => {
  const hooks = getHookNames(events, configuration.hookNames);
  const runtime = JSON.stringify(configuration.runtime ?? DEFAULT_RUNTIME);
  const extension = configuration.imports?.extension ?? "js";
  const eventModule = JSON.stringify(
    getImportSpecifier(
      configuration.output,
      configuration.events.file,
      extension,
    ),
  );
  const dispatcherModule = JSON.stringify(
    getImportSpecifier(
      configuration.output,
      configuration.dispatcher.file,
      extension,
    ),
  );
  const sibling = (name: string) =>
    JSON.stringify(extension === "none" ? `./${name}` : `./${name}.js`);
  const files = new Map<string, string>();

  hooks.forEach(({ event, name }) => {
    files.set(
      `${name}.ts`,
      `${GENERATED_HEADER}import type { ChannelInput, PublicationHandler, UseChannelOptions } from ${runtime};
import type { ${importBinding(configuration.events.type, "RealtimeEvents")} } from ${eventModule};
import { ${importBinding(configuration.dispatcher.export, "useChannelEvent")} } from ${dispatcherModule};

type EventDefinition = RealtimeEvents[${JSON.stringify(event)}];

export const ${name} = (
  channel: ChannelInput<EventDefinition["channel"]>,
  onEvent: PublicationHandler<EventDefinition["payload"]>,
  options: UseChannelOptions<EventDefinition["payload"]> = {},
) => {
  return useChannelEvent(channel, ${JSON.stringify(event)}, onEvent, options);
};
`,
    );
  });

  const exports = hooks
    .map(({ name }) => `export { ${name} } from ${sibling(name)};`)
    .join("\n");
  files.set("index.ts", `${GENERATED_HEADER}${exports}\n`);

  return files;
};
